version: "3.8"
services:
  teamspeak:
    image: enucatl/teamspeak-vpn
    environment:
      - TS3SERVER_LICENSE=accept
    volumes:
      - data:/data
      - config:/config
    ports:
      - 9987:9987/udp
    restart: unless-stopped

volumes:
  data:
  config:
