version: "3.8"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  teamspeak:
    image: mbentley/teamspeak:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TS3SERVER_LICENSE=accept
    volumes:
      - data:/data
    ports:
      - 9987:9987/udp
    restart: unless-stopped

volumes:
  data:
  config:
