version: "3.8"
services:
  wireguard:
    image: linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1
    healthcheck:
      test: curl -s https://am.i.mullvad.net/connected | grep -v "not connected"
      interval: 600s
      retries: 1
      start_period: 10s
      timeout: 30s
    ports:
      - 9987:9987/udp
    restart: unless-stopped

  teamspeak:
    image: mbentley/teamspeak:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TS3SERVER_LICENSE=accept
    volumes:
      - data:/data
    restart: unless-stopped
    network_mode: service:wireguard
    depends_on:
      wireguard:
        condition: service_healthy

volumes:
  data:
  config:
