version: "3.8"
services:

  teamspeak:
    image: mbentley/teamspeak:debian
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TS3SERVER_LICENSE=accept
    volumes:
      - data:/data
    restart: unless-stopped
    ports:
      - 9987:9987/udp

volumes:
  data:
