version: "3.8"
services:
  teamspeak:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    image: enucatl/teamspeak-vpn
    environment:
      - TS_DIRECTORY=/opt/teamspeak
      - TS3SERVER_LICENSE=accept
    volumes:
      - data:/data
      - config:/config
    ports:
      - 9987:9987/udp
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  data:
  config:
