services:

  teamspeak:
    extends:
      file: ../compose-security-baseline/hardening.yml
      service: hardened-medium
    user: 9987:9987
    image: teamspeak:latest
    tmpfs:
      - /var/run/ts3server:rw,noexec,nosuid,nodev,size=8m,uid=9987,gid=9987,mode=0700
    cpu_shares: 1024
    environment:
      - TS3SERVER_DB_PLUGIN=ts3db_sqlite3
      - TS3SERVER_DB_SQLCREATEPATH=create_sqlite3
      - TS3SERVER_LICENSE=accept
    volumes:
      - ts3server:/var/ts3server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10011"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s
    ports:
      - 9987:9987/udp
    networks:
      - default
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  ts3server:

networks:
  default:
    enable_ipv6: true
    driver_opts:
      com.docker.network.endpoint.sysctls: '{"net.ipv6.conf.eth0.proxy_ndp": "1"}'
